Repository Tejashri-Taral/TrendTrove-Ecommerce, pull requests merged in 2024-11, with the labels that each got.

#682 ENHANCING THE ACCESSORIES PRODUCTS SAME LIKE OTHER PAGES
  accessories.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#717 Overlapping of content fixed
  Boy.html
  accessories.html
  child.html
  mens.html
  style.css
Labels: gssoc-ext, level2

#734 Enhance Return and Refund Policy Section with Card Layout and Hover Effects
  return-policy.html
Labels: gssoc-ext, level1

#728 UI Fixes on the main page .
  index.html
  style.css
Labels: gssoc-ext, level1

#677 updated the login and signup form
  login-sginup.html
Labels: gssoc-ext, level1

#750 Added dark mode to All pages. Issue#81
  Style/popup.css
  about.html
  contact.html
  day-mode.png
  features.html
  index.html
  mens.html
  moon.png
  style.css
Labels: gssoc-ext, level2

#730 Added toggle button
  about.html
  index.html
  style.css
Labels: gssoc-ext, level1

#755 Added Enhanced scroll back button with progress ring to ALL pages
  Boy.html
  about.html
  accessories.html
  child.html
  contact.html
  features.html
  index.html
  mens.html
  womens.html
Labels: gssoc-ext, level2

#777 fixed dark mode
  about.html
  features.html
  index.html
  style.css
  styles.css
Labels: gssoc-ext, level1

#776 FIX: 775 : Added header and footer
  faq.html
Labels: gssoc-ext, level1

#772 added button cart and rating
  index.html
Labels: gssoc-ext, level1

#789 Added the visitor Counter
  index.html
  style.css
Labels: gssoc-ext, level1

#788 issue number #773 is solved
  style.css
Labels: gssoc-ext, level1

#801 upated cart page
  cart.html
  index.html
Labels: gssoc-ext, level1

#802 About page responsiveness issue is solved, issue #771 is solved
  about.html
Labels: gssoc-ext, level1

#796 Created Site Map Page
  index.html
  sitemap.html
Labels: gssoc-ext, level2

#811 Added buy now functionality
  cart.html
  products/bags.html
Labels: gssoc-ext, level1

#799 Fixed footer in About page (fixes #735)
  about.html
  styles.css
Labels: gssoc-ext, level1

#798 changed font style in footer
  index.html
  style.css
Labels: gssoc-ext, level1

#806 fixes #791 [overlapping visitor counts and social media links]
  style.css
Labels: gssoc-ext, level1

#815 Add Hover Effect to Main Heading for Dynamic Appearance
  index.html
Labels: gssoc-ext, level1

#809 Changes made to the dark theme
  index.html
Labels: gssoc-ext, level1

#804 Update and Enhancement of UI
  Style/about.css
  about.html
  contact.html
  features.html
  index.html
  style.css
Labels: gssoc-ext, level1

#817 Add scale-up hover effect for images in the about section
  about.html
Labels: gssoc-ext, level1

#818 feat: Added icons to quickinks
  Boy.html
  about.html
  accessories.html
  child.html
  contact.html
  contributors.html
  faq.html
  features.html
  feedback.html
  index.html
  mens.html
  privacy.html
  return-policy.html
  terms-conditions.html
  womens.html
Labels: gssoc-ext, level2
