Repository Tejashri-Taral/TrendTrove-Ecommerce, pull requests merged in 2024-10, with the labels that each got.

#17 add contact page
  contact.html
  index.html
  style.css
Labels: level2

#41 Add link to login/signup page in navigation
  index.html
  login-sginup.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#18 Subscribe to Newsletter Buttons Alignment Fixed
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#60 Improve Social Media Icon Design and added animation.
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#91 Added sneaker.html and css with images #27
  Style/sneaker.css
  images/img1.jpg
  images/img10.jpg
  images/img11.jpg
  images/img12.jpg
  images/img2.jpg
  images/img3.jpg
  images/img4.jpg
  images/img5.jpg
  images/img6.jpg
  images/img7.jpg
  images/img8.jpg
  images/img9.jpg
  index.html
  sneaker.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#75 Adding Copyright Information to the Footer.
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#118 logo is added
  images/logo.png
  images/logo1.png
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#42 Fixed Wishlist icon, name and price highlighting and hover animation timing
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#131 CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#107 Fixed the appearance and response of nav bar
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#130 add mens.html and womens.html file#43
  .vscode/settings.json
  about.html
  contact.html
  index.html
  mens.html
  style.css
  womens.html
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level3

#129 Add Features page to the website
  features.html
  index.html
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#177 Enhance Sneakers Page with Filters and New Listings
  images/img13.jpg
  images/img14.jpg
  images/img15.jpg
  images/img16.jpg
  images/img17.jpg
  images/img18.jpg
  images/img19.jpg
  images/img20.jpg
  sneaker.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#183 Added The Terms and conditions page
  about.html
  contact.html
  index.html
  style.css
  terms-conditions.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#40 added the functionality to search and user icon
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#184 Added a Scroll "Progress Indicator Bar"
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#219 Added the animations to the buttons #94
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#226 added FAQ section in quick links at footer
  faq.html
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#217 enhanced the navbar
  about.html
  contact.html
  features.html
  index.html
  sneaker.html
  style.css
  styles.css
  terms-conditions.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#180 Issue resolved #137
  feedback.html
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#239 Feature Return policy 156
  about.html
  contact.html
  features.html
  index.html
  mens.html
  return-policy.html
  style.css
  terms-conditions.html
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#246 conflicts resolved and issue resolved #28
  index.html
  mens.html
  style.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#261 Update login-sginup.html
  login-sginup.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#181 Enhanced About Page
  about.html
  images/about1.jpg
  images/about2.jpg
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#251 Added anchor to webpages, fixed issue #87
  about.html
  contact.html
  login-sginup.html
  mens.html
  return-policy.html
  terms-conditions.html
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#257 added add-to-cart button to mens,women page
  mens.html
  style.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#279 Sandals page, Sunglasses page, Bags page #165
  Style/bags.css
  Style/sandals.css
  Style/sunglasses.css
  images/bag1.jpg
  images/bag2.jpg
  images/bag3.jpg
  images/bag4.jpg
  images/bag5.jpg
  images/bag6.jpg
  images/bag7.jpg
  images/bag8.jpg
  images/bag9.jpg
  images/customer1.jpg
  images/customer2.jpg
  images/customer3.jpg
  images/sandal1.jpg
  images/sandal2.jpg
  images/sandal3.jpg
  images/sandal4.jpg
  images/sandal5.jpg
  images/sandal6.jpg
  images/sandal7.jpg
  images/sandal8.jpg
  images/sunglasses1.jpg
  images/sunglasses2.jpg
  images/sunglasses3.jpg
  images/sunglasses4.jpg
  images/sunglasses5.jpg
  images/sunglasses6.jpg
  images/sunglasses7.jpg
  images/sunglasses8.jpg
  index.html
  products/bags.html
  products/sandals.html
  products/sunglasses.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#307 Changes colour of input box when it is active
  login-sginup.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#325 made the navbar same as home page
  mens.html
  style.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#286 ALIGNMENT and ENHANCEMENT of all men products
  mens.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#252 [BUG] Smooth Scrolling and Product Nav link fix
  about.html
  contact.html
  index.html
  sneaker.html
  style.css
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#312 Navbar changes under Products Tab
  about.html
  contact.html
  features.html
  index.html
Labels: gssoc-ext

#333 [Feat] Bug & Feature Preset Added
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#332 navbar updated in return policy page
  return-policy.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#339 Issue:- #277 [Solved] :- Improved UI of About us page.
  about.html
  images/about3.jpg
  images/about4.jpg
Labels: gssoc-ext, hacktoberfest-accepted, level1

#337 navbar integrated successfully in product pages
  products/bags.html
  products/productscss.css
  products/sandals.html
  products/sunglasses.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#349 Kid Section Added
  Boy.html
  child.html
  images/Black Denim Joggers.webp
  images/Black Formal Shoes.webp
  images/Bottom Wear.jpeg
  images/Boy Sneakers.jpeg
  images/Boys Loafer.webp
  images/Casual Camouflage Jogger.jpeg
  images/Casual Shoes.jpg
  images/Elastic Waist Jeans.jpg
  images/Leather Shoes.jpg
  images/Light Weight boys slippers.webp
  images/Net Sequins Embroidered.jpg
  images/Pamper pants.jpeg
  images/Stylish Shoes.jpg
  images/Trendy Bottoms.jpg
  images/Trouser for Boys.webp
  images/bazufrill.webp
  images/booties.webp
  images/bottomwear.htm
  images/boy printed tshirt.jpg
  images/boys round neck tshirt.webp
  images/butterfly.jpg
  images/check shirt.webp
  images/childbanner.jpg
  images/chinatrade.avif
  images/clothingEthnic.webp
  images/cotton partywearkid2.webp
  images/embroided straigh kurta.webp
  images/fancy boy slipper.avif
  images/floralpattern.jpeg
  images/frill.jpg
  images/full sleeve shirt.webp
  images/girl banner.jpg
  images/girl leather.jpg
  images/girl sandals.jpg
  images/girl shoes.webp
  images/girls track pants.jpg
  images/green colour jacquard silk kurta.jpeg
  images/high heels.jpeg
  images/kids-girl-tops1.jpg
  images/kids-girls-baby-western-top-for-women-full.jpg
  images/kidsplazzo.webp
  images/kurta set.jpg
  images/light up toddler       girl.webp
  images/pocket Mild Wash Bermuda Shorts.jpg_2000Wx3000H
  images/pocketSolidShorts.webp
  images/printedlegging.webp
  images/printedpuffsleeves.webp
  images/pumps shoes.jpg
  images/rio girls tie and dye shirt.webp
  images/shortboys.png
  images/shorts.jpg
  images/sifli sikvans boy kurta.webp
  images/toddler girl sandals.jpg
  images/twg.jpeg
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#359 added the github greeting bot
  .github/ISSUE_TEMPLATE/greetings.yml
  .github/ISSUE_TEMPLATE/pr-comment.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#350 Contact page update
  contact.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#361 issue #143 [FEATURE] Show Newsletter Subscription Confirmation Message solved
  about.html
  features.html
  images/confirmation.png
  index.html
  mens.html
  return-policy.html
  style.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#328 Issue resolved#253 added save & share buttons
  mens.html
  style.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#382 Issue #378 Solved :- Pop up Added succesfully.
  Style/popup.css
  images/popup1.jpg
  index.html
  script/popup.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#387 Adding the Social Media in all the footer Section.
  .vscode/settings.json
  about.html
  contact.html
  return-policy.html
  terms-conditions.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#395 ✨issue #372 solved contact page improved✨
  contact.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#406 #377 Fixed heart hover
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#417 improve scroll bar and preloader
  Boy.html
  about.html
  child.html
  contact.html
  features.html
  index.html
  login-sginup.html
  mens.html
  preloader.js
  preloaderStyle.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#429 alignment corrected
  mens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#424 Make a page for the shop clothing.
  images/cloth1.jpeg
  images/cloth10.jpeg
  images/cloth11.jpeg
  images/cloth12.jpeg
  images/cloth13.jpeg
  images/cloth14.jpeg
  images/cloth15.jpeg
  images/cloth16.jpeg
  images/cloth17.jpeg
  images/cloth18.jpeg
  images/cloth19.jpeg
  images/cloth2.jpeg
  images/cloth20.jpeg
  images/cloth3.jpeg
  images/cloth4.jpeg
  images/cloth5.jpeg
  images/cloth6.jpeg
  images/cloth7.jpeg
  images/cloth8.jpeg
  images/cloth9.jpeg
  index.html
  shopclothing.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#407 ALIGN AND ENHANCE ALL PRODUCTS IN WOMENS BOY'S & CHILD'S PAGES
  Boy.html
  child.html
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#442 Added Accessories page
  accessories.html
  images/SALEACC.png
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#479 [Feat]: Add Dyanamic date functionality to copyright footer section
  index.html
Labels: hacktoberfest-accepted

#472 Resdesigned the contact page and made it responsive for all devices
  Style/contact.css
  contact.html
  images/trendlogo_white_on_black.png
Labels: gssoc-ext, hacktoberfest-accepted, level2

#280 Added hover effect to quick links section
  about.html
  contact.html
  features.html
  index.html
  mens.html
  style.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#488 Fix issue #340: Add to cart button corrected
  mens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#511 Created bot for new issue creation
  .github/workflows/autocomment-issuecreation.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#493 enhanced design
  about.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#540 Rectified the bug as there is a presence of the quick links twice
  about.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#538 Update feedback.html
  feedback.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#539 Create Code_of_Conduct.md
  Code_of_Conduct.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#571 Added Scroll-back button to all the pages
  about.html
  contact.html
  features.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#553 Size filter is working in Shop clothing Section
  shopclothing.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#546 Fix: Update Links for Terms and Privacy in Login-Signup Page
  index.html
  login-sginup.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#597 "Shop From The Gram" the card and its images resizing issue fixed
  index.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#578 Add Privacy Page and Link in Index/Login/Signup
  index.html
  login-sginup.html
  privacy.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#577 Updated the readme file with the featured in, repo review table and our contributors
  README.md
  contributors.css
  contributors.html
  contributors.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#550 add tooltips on the contact form
  contact.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#572 Map in Contact page now responsive
  contact.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#549 #534 Issue Solved - Added Translator Tool
  Style/about.css
  about.html
  contact.html
  features.html
  feedback.html
  index.html
  mens.html
  script/modal_box.js
  sneaker.html
  terms-conditions.html
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#552 Add login link to navigation in all required pages
  about.html
  contact.html
  products/bags.html
  products/sandals.html
  products/sunglasses.html
  return-policy.html
  shopclothing.html
  sneaker.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#595 I have changed the UI section of feature section.
  styles.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#622 blog page bug it fixed
  about.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#637 Added Cart Page for Cart Icon in Navbar
  about.html
  cart.html
  contact.html
  features.html
  index.html
  mens.html
  return-policy.html
  sneaker.html
  terms-conditions.html
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#663 added button google facbook and X
  login-sginup.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#661 #623 solved: added kids and accessories sections under products tab
  about.html
  contact.html
  features.html
  privacy.html
  return-policy.html
  shopclothing.html
  sneaker.html
  terms-conditions.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#665 Adjusted Filter Box Sizes for Better UI
  index.html
  shopclothing.html
  sneaker.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#688 ✔️Added Scroll Progress bar into the website
  Boy.html
  Style/about.css
  Style/bags.css
  Style/sandals.css
  Style/sneaker.css
  Style/sunglasses.css
  about.html
  accessories.html
  cart.html
  child.html
  contact.html
  contributors.css
  contributors.html
  faq.html
  features.html
  index.html
  login-sginup.html
  mens.html
  privacy.html
  products/productscss.css
  return-policy.html
  script/progressbar.js
  shopclothing.html
  sneaker.html
  style.css
  styles.css
  terms-conditions.html
  womens.html
Labels: hacktoberfest-accepted

#692 Update README.md added Stargazers and Forkers section
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#694 solve [Feat]: Designing Feedback Form Page and Adding Navbar and Footer to It #639
  feedback.html
  index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#696 Extended FAQs Section for Improved Buyer Communication
  faq.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#695 features page added
  features.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#713 Improve Hover Effect on Accessories Page Cards
  accessories.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#706 Navbar fixed on top.
  index.html
  script/progressbar.js
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#700 solved #660 fixed glitching share box on hero section
  accessories.html
  mens.html
  script/share-button.js
  style.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#725 updated the footer
  accessories.html
  style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#724 Add to cart functionality
  cart.html
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#716 Proper aligning of login ans signup pages
  login-sginup.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#727 added rating in the product
  Boy.html
  accessories.html
  child.html
  mens.html
  style.css
  styles.css
  womens.html
Labels: gssoc-ext, hacktoberfest-accepted, level2
